const products = [
  {id:'p1',name:'Naruto Uzumaki Hoodie',price:1999,img:'🎌',tag:'Apparel',type:'hoodie',category:'Apparel',desc:'Premium oversized hoodie',isNew:true,anime:'Naruto'},
  {id:'p2',name:'Naruto Streetwear Tee',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Streetwear anime tee',isNew:false,anime:'Naruto'},
  {id:'p3',name:'Naruto Phone Cover',price:299,img:'📱',tag:'Accessories',type:'phone',category:'Accessories',desc:'Protective phone case',isNew:false,anime:'Naruto'},
  {id:'p4',name:'Naruto Figurine',price:1899,img:'🗿',tag:'Figurines',type:'figurine',category:'Figurines',desc:'Collectible figurine',isNew:false,anime:'Naruto'},
  {id:'p5',name:'One Piece Luffy Hoodie',price:2099,img:'🎌',tag:'Apparel',type:'hoodie',category:'Apparel',desc:'Oversized hoodie',isNew:true,anime:'One Piece'},
  {id:'p6',name:'One Piece Pirate Tee',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Streetwear tee',isNew:false,anime:'One Piece'},
  {id:'p7',name:'One Piece Phone Cover',price:299,img:'📱',tag:'Accessories',type:'phone',category:'Accessories',desc:'Phone case',isNew:false,anime:'One Piece'},
  {id:'p8',name:'One Piece Figurine',price:1999,img:'🗿',tag:'Figurines',type:'figurine',category:'Figurines',desc:'Collectible figurine',isNew:false,anime:'One Piece'},
  {id:'p9',name:'Jujutsu Kaisen Gojo Hoodie',price:2199,img:'🎌',tag:'Apparel',type:'hoodie',category:'Apparel',desc:'Premium hoodie',isNew:true,anime:'Jujutsu Kaisen'},
  {id:'p10',name:'Jujutsu Kaisen Tee',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Tee shirt',isNew:false,anime:'Jujutsu Kaisen'},
  {id:'p11',name:'Jujutsu Kaisen Phone',price:299,img:'📱',tag:'Accessories',type:'phone',category:'Accessories',desc:'Phone cover',isNew:false,anime:'Jujutsu Kaisen'},
  {id:'p12',name:'Jujutsu Kaisen Figurine',price:1999,img:'🗿',tag:'Figurines',type:'figurine',category:'Figurines',desc:'Figurine',isNew:false,anime:'Jujutsu Kaisen'},
  {id:'p13',name:'AoT Scout Hoodie',price:2099,img:'🎌',tag:'Apparel',type:'hoodie',category:'Apparel',desc:'Scout regiment hoodie',isNew:true,anime:'Attack on Titan'},
  {id:'p14',name:'AoT Wings Tee',price:749,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Wings design tee',isNew:false,anime:'Attack on Titan'},
  {id:'p15',name:'AoT Phone Cover',price:299,img:'📱',tag:'Accessories',type:'phone',category:'Accessories',desc:'Phone cover',isNew:false,anime:'Attack on Titan'},
  {id:'p16',name:'AoT Figurine',price:1999,img:'🗿',tag:'Figurines',type:'figurine',category:'Figurines',desc:'Figurine',isNew:false,anime:'Attack on Titan'},
  {id:'p17',name:'Demon Slayer Hoodie',price:1999,img:'🎌',tag:'Apparel',type:'hoodie',category:'Apparel',desc:'Premium hoodie',isNew:true,anime:'Demon Slayer'},
  {id:'p18',name:'Demon Slayer Tee',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Tee shirt',isNew:false,anime:'Demon Slayer'},
  {id:'p19',name:'Demon Slayer Phone',price:299,img:'📱',tag:'Accessories',type:'phone',category:'Accessories',desc:'Phone cover',isNew:false,anime:'Demon Slayer'},
  {id:'p20',name:'Demon Slayer Figurine',price:2199,img:'🗿',tag:'Figurines',type:'figurine',category:'Figurines',desc:'Figurine',isNew:true,anime:'Demon Slayer'},
  {id:'p21',name:'Dragon Ball Hoodie',price:1999,img:'🎌',tag:'Apparel',type:'hoodie',category:'Apparel',desc:'Goku hoodie',isNew:false,anime:'Dragon Ball'},
  {id:'p22',name:'Dragon Ball Tee',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Saiyan tee',isNew:false,anime:'Dragon Ball'},
  {id:'p23',name:'Dragon Ball Phone',price:299,img:'📱',tag:'Accessories',type:'phone',category:'Accessories',desc:'Phone cover',isNew:false,anime:'Dragon Ball'},
  {id:'p24',name:'Dragon Ball Figurine',price:1899,img:'🗿',tag:'Figurines',type:'figurine',category:'Figurines',desc:'Goku figurine',isNew:false,anime:'Dragon Ball'},
  {id:'p25',name:'Tokyo Revengers Hoodie',price:2099,img:'🎌',tag:'Apparel',type:'hoodie',category:'Apparel',desc:'Premium hoodie',isNew:true,anime:'Tokyo Revengers'},
  {id:'p26',name:'Tokyo Revengers Tee',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Tee shirt',isNew:false,anime:'Tokyo Revengers'},
  {id:'p27',name:'Tokyo Revengers Phone',price:299,img:'📱',tag:'Accessories',type:'phone',category:'Accessories',desc:'Phone cover',isNew:false,anime:'Tokyo Revengers'},
  {id:'p28',name:'Tokyo Revengers Figurine',price:1899,img:'🗿',tag:'Figurines',type:'figurine',category:'Figurines',desc:'Figurine',isNew:false,anime:'Tokyo Revengers'},
  {id:'p29',name:'Chainsaw Man Hoodie',price:2099,img:'🎌',tag:'Apparel',type:'hoodie',category:'Apparel',desc:'Premium hoodie',isNew:true,anime:'Chainsaw Man'},
  {id:'p30',name:'Chainsaw Man Tee',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Tee shirt',isNew:false,anime:'Chainsaw Man'},
  {id:'p31',name:'Chainsaw Man Phone',price:299,img:'📱',tag:'Accessories',type:'phone',category:'Accessories',desc:'Phone cover',isNew:false,anime:'Chainsaw Man'},
  {id:'p32',name:'Chainsaw Man Figurine',price:1899,img:'🗿',tag:'Figurines',type:'figurine',category:'Figurines',desc:'Figurine',isNew:false,anime:'Chainsaw Man'},
  {id:'p33',name:'Bleach Hoodie',price:2099,img:'🎌',tag:'Apparel',type:'hoodie',category:'Apparel',desc:'Ichigo hoodie',isNew:true,anime:'Bleach'},
  {id:'p34',name:'Bleach Tee',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Soul Reaper tee',isNew:false,anime:'Bleach'},
  {id:'p35',name:'Bleach Phone',price:299,img:'📱',tag:'Accessories',type:'phone',category:'Accessories',desc:'Phone cover',isNew:false,anime:'Bleach'},
  {id:'p36',name:'Bleach Figurine',price:1899,img:'🗿',tag:'Figurines',type:'figurine',category:'Figurines',desc:'Figurine',isNew:false,anime:'Bleach'},
  {id:'p37',name:'Berserk Hoodie',price:2199,img:'🎌',tag:'Apparel',type:'oversized',category:'Apparel',desc:'Oversized hoodie',isNew:true,anime:'Berserk'},
  {id:'p38',name:'Berserk Tee',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Tee shirt',isNew:false,anime:'Berserk'},
  {id:'p39',name:'Berserk Phone',price:299,img:'📱',tag:'Accessories',type:'phone',category:'Accessories',desc:'Phone cover',isNew:false,anime:'Berserk'},
  {id:'p40',name:'Berserk Figurine',price:1899,img:'🗿',tag:'Figurines',type:'figurine',category:'Figurines',desc:'Figurine',isNew:false,anime:'Berserk'},
  {id:'p41',name:'MHA Hoodie',price:1999,img:'🎌',tag:'Apparel',type:'hoodie',category:'Apparel',desc:'My Hero Academia',isNew:true,anime:'My Hero Academia'},
  {id:'p42',name:'MHA Tee',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Hero tee',isNew:false,anime:'My Hero Academia'},
  {id:'p43',name:'MHA Phone',price:299,img:'📱',tag:'Accessories',type:'phone',category:'Accessories',desc:'Phone cover',isNew:false,anime:'My Hero Academia'},
  {id:'p44',name:'MHA Figurine',price:1899,img:'🗿',tag:'Figurines',type:'figurine',category:'Figurines',desc:'Figurine',isNew:false,anime:'My Hero Academia'},
  {id:'p45',name:'Solo Leveling Hoodie',price:2099,img:'🎌',tag:'Apparel',type:'oversized',category:'Apparel',desc:'Premium oversized',isNew:true,anime:'Solo Leveling'},
  {id:'p46',name:'Solo Leveling Tee',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Tee shirt',isNew:false,anime:'Solo Leveling'},
  {id:'p47',name:'Solo Leveling Phone',price:299,img:'📱',tag:'Accessories',type:'phone',category:'Accessories',desc:'Phone cover',isNew:false,anime:'Solo Leveling'},
  {id:'p48',name:'Solo Leveling Figurine',price:1999,img:'🗿',tag:'Figurines',type:'figurine',category:'Figurines',desc:'Figurine',isNew:false,anime:'Solo Leveling'},
  {id:'p49',name:'Anime Street Hoodie',price:1999,img:'🎌',tag:'Apparel',type:'hoodie',category:'Apparel',desc:'Streetwear',isNew:false,anime:'Mixed'},
  {id:'p50',name:'Anime Graphic Tee',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Graphic design',isNew:false,anime:'Mixed'},
  {id:'p51',name:'Anime Oversized 1',price:2199,img:'🎌',tag:'Apparel',type:'oversized',category:'Apparel',desc:'Oversized fit',isNew:true,anime:'Mixed'},
  {id:'p52',name:'Anime Oversized 2',price:2199,img:'🎌',tag:'Apparel',type:'oversized',category:'Apparel',desc:'Oversized fit',isNew:true,anime:'Mixed'},
  {id:'p53',name:'Anime Jacket 1',price:3999,img:'🧥',tag:'Apparel',type:'jacket',category:'Apparel',desc:'Premium jacket',isNew:true,anime:'Mixed'},
  {id:'p54',name:'Anime Jacket 2',price:3999,img:'🧥',tag:'Apparel',type:'jacket',category:'Apparel',desc:'Premium jacket',isNew:true,anime:'Mixed'},
  {id:'p55',name:'Otaku Hoodie 1',price:2099,img:'🎌',tag:'Apparel',type:'hoodie',category:'Apparel',desc:'Premium hoodie',isNew:false,anime:'Mixed'},
  {id:'p56',name:'Otaku Tee 1',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Graphic tee',isNew:false,anime:'Mixed'},
  {id:'p57',name:'Otaku Phone 1',price:299,img:'📱',tag:'Accessories',type:'phone',category:'Accessories',desc:'Phone cover',isNew:false,anime:'Mixed'},
  {id:'p58',name:'Otaku Figurine 1',price:1999,img:'🗿',tag:'Figurines',type:'figurine',category:'Figurines',desc:'Collectible',isNew:false,anime:'Mixed'},
  {id:'p59',name:'Shonen Hoodie 1',price:1999,img:'🎌',tag:'Apparel',type:'hoodie',category:'Apparel',desc:'Shonen style',isNew:false,anime:'Mixed'},
  {id:'p60',name:'Shonen Tee 1',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Tee shirt',isNew:false,anime:'Mixed'},
  {id:'p61',name:'Shonen Phone 1',price:299,img:'📱',tag:'Accessories',type:'phone',category:'Accessories',desc:'Phone cover',isNew:false,anime:'Mixed'},
  {id:'p62',name:'Shonen Figurine 1',price:1899,img:'🗿',tag:'Figurines',type:'figurine',category:'Figurines',desc:'Figurine',isNew:false,anime:'Mixed'},
  {id:'p63',name:'Culture Hoodie 1',price:2099,img:'🎌',tag:'Apparel',type:'hoodie',category:'Apparel',desc:'Cultural design',isNew:false,anime:'Mixed'},
  {id:'p64',name:'Culture Tee 1',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Design tee',isNew:false,anime:'Mixed'},
  {id:'p65',name:'Culture Phone 1',price:299,img:'📱',tag:'Accessories',type:'phone',category:'Accessories',desc:'Phone cover',isNew:false,anime:'Mixed'},
  {id:'p66',name:'Culture Figurine 1',price:1999,img:'🗿',tag:'Figurines',type:'figurine',category:'Figurines',desc:'Figurine',isNew:false,anime:'Mixed'},
  {id:'p67',name:'Street Hoodie 1',price:1999,img:'🎌',tag:'Apparel',type:'hoodie',category:'Apparel',desc:'Street style',isNew:false,anime:'Mixed'},
  {id:'p68',name:'Street Tee 1',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Tee shirt',isNew:false,anime:'Mixed'},
  {id:'p69',name:'Street Phone 1',price:299,img:'📱',tag:'Accessories',type:'phone',category:'Accessories',desc:'Phone cover',isNew:false,anime:'Mixed'},
  {id:'p70',name:'Street Figurine 1',price:1899,img:'🗿',tag:'Figurines',type:'figurine',category:'Figurines',desc:'Figurine',isNew:false,anime:'Mixed'},
  {id:'p71',name:'Hero Hoodie 1',price:1999,img:'🎌',tag:'Apparel',type:'hoodie',category:'Apparel',desc:'Hero themed',isNew:false,anime:'Mixed'},
  {id:'p72',name:'Hero Tee 1',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Tee shirt',isNew:false,anime:'Mixed'},
  {id:'p73',name:'Hero Phone 1',price:299,img:'📱',tag:'Accessories',type:'phone',category:'Accessories',desc:'Phone cover',isNew:false,anime:'Mixed'},
  {id:'p74',name:'Hero Figurine 1',price:1899,img:'🗿',tag:'Figurines',type:'figurine',category:'Figurines',desc:'Figurine',isNew:false,anime:'Mixed'},
  {id:'p75',name:'Legend Hoodie 1',price:2099,img:'🎌',tag:'Apparel',type:'oversized',category:'Apparel',desc:'Legend series',isNew:true,anime:'Mixed'},
  {id:'p76',name:'Legend Tee 1',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Tee shirt',isNew:false,anime:'Mixed'},
  {id:'p77',name:'Legend Phone 1',price:299,img:'📱',tag:'Accessories',type:'phone',category:'Accessories',desc:'Phone cover',isNew:false,anime:'Mixed'},
  {id:'p78',name:'Legend Figurine 1',price:1999,img:'🗿',tag:'Figurines',type:'figurine',category:'Figurines',desc:'Figurine',isNew:false,anime:'Mixed'},
  {id:'p79',name:'Spirit Hoodie 1',price:1999,img:'🎌',tag:'Apparel',type:'hoodie',category:'Apparel',desc:'Spirit themed',isNew:false,anime:'Mixed'},
  {id:'p80',name:'Spirit Tee 1',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Tee shirt',isNew:false,anime:'Mixed'},
  {id:'p81',name:'Spirit Phone 1',price:299,img:'📱',tag:'Accessories',type:'phone',category:'Accessories',desc:'Phone cover',isNew:false,anime:'Mixed'},
  {id:'p82',name:'Spirit Figurine 1',price:1899,img:'🗿',tag:'Figurines',type:'figurine',category:'Figurines',desc:'Figurine',isNew:false,anime:'Mixed'},
  {id:'p83',name:'Power Hoodie 1',price:2099,img:'🎌',tag:'Apparel',type:'hoodie',category:'Apparel',desc:'Power design',isNew:true,anime:'Mixed'},
  {id:'p84',name:'Power Tee 1',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Tee shirt',isNew:false,anime:'Mixed'},
  {id:'p85',name:'Power Phone 1',price:299,img:'📱',tag:'Accessories',type:'phone',category:'Accessories',desc:'Phone cover',isNew:false,anime:'Mixed'},
  {id:'p86',name:'Power Figurine 1',price:1999,img:'🗿',tag:'Figurines',type:'figurine',category:'Figurines',desc:'Figurine',isNew:false,anime:'Mixed'},
  {id:'p87',name:'Warrior Hoodie 1',price:1999,img:'🎌',tag:'Apparel',type:'hoodie',category:'Apparel',desc:'Warrior style',isNew:false,anime:'Mixed'},
  {id:'p88',name:'Warrior Tee 1',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Tee shirt',isNew:false,anime:'Mixed'},
  {id:'p89',name:'Warrior Phone 1',price:299,img:'📱',tag:'Accessories',type:'phone',category:'Accessories',desc:'Phone cover',isNew:false,anime:'Mixed'},
  {id:'p90',name:'Warrior Figurine 1',price:1899,img:'🗿',tag:'Figurines',type:'figurine',category:'Figurines',desc:'Figurine',isNew:false,anime:'Mixed'},
  {id:'p91',name:'Shadow Hoodie 1',price:2099,img:'🎌',tag:'Apparel',type:'oversized',category:'Apparel',desc:'Shadow design',isNew:true,anime:'Mixed'},
  {id:'p92',name:'Shadow Tee 1',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Tee shirt',isNew:false,anime:'Mixed'},
  {id:'p93',name:'Shadow Phone 1',price:299,img:'📱',tag:'Accessories',type:'phone',category:'Accessories',desc:'Phone cover',isNew:false,anime:'Mixed'},
  {id:'p94',name:'Shadow Figurine 1',price:1899,img:'🗿',tag:'Figurines',type:'figurine',category:'Figurines',desc:'Figurine',isNew:false,anime:'Mixed'},
  {id:'p95',name:'Dragon Hoodie 1',price:1999,img:'🎌',tag:'Apparel',type:'hoodie',category:'Apparel',desc:'Dragon series',isNew:false,anime:'Mixed'},
  {id:'p96',name:'Dragon Tee 1',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Tee shirt',isNew:false,anime:'Mixed'},
  {id:'p97',name:'Dragon Phone 1',price:299,img:'📱',tag:'Accessories',type:'phone',category:'Accessories',desc:'Phone cover',isNew:false,anime:'Mixed'},
  {id:'p98',name:'Dragon Figurine 1',price:1999,img:'🗿',tag:'Figurines',type:'figurine',category:'Figurines',desc:'Dragon collectible',isNew:false,anime:'Mixed'},
  {id:'p99',name:'Storm Hoodie 1',price:2099,img:'🎌',tag:'Apparel',type:'oversized',category:'Apparel',desc:'Storm design',isNew:true,anime:'Mixed'},
  {id:'p100',name:'Storm Tee 1',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Tee shirt',isNew:false,anime:'Mixed'},
  {id:'p101',name:'Blade Hoodie 1',price:1999,img:'🎌',tag:'Apparel',type:'jacket',category:'Apparel',desc:'Blade jacket',isNew:true,anime:'Mixed'},
  {id:'p102',name:'Blade Tee 1',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Tee shirt',isNew:false,anime:'Mixed'},
  {id:'p103',name:'Flame Hoodie 1',price:2099,img:'🎌',tag:'Apparel',type:'hoodie',category:'Apparel',desc:'Flame design',isNew:true,anime:'Mixed'},
  {id:'p104',name:'Flame Tee 1',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Tee shirt',isNew:false,anime:'Mixed'},
  {id:'p105',name:'Eclipse Hoodie 1',price:1999,img:'🎌',tag:'Apparel',type:'oversized',category:'Apparel',desc:'Eclipse series',isNew:false,anime:'Mixed'},
  {id:'p106',name:'Eclipse Tee 1',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Tee shirt',isNew:false,anime:'Mixed'},
  {id:'p107',name:'Phantom Hoodie 1',price:1999,img:'🎌',tag:'Apparel',type:'hoodie',category:'Apparel',desc:'Phantom design',isNew:true,anime:'Mixed'},
  {id:'p108',name:'Phantom Tee 1',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Tee shirt',isNew:false,anime:'Mixed'},
  {id:'p109',name:'Galaxy Hoodie 1',price:2099,img:'🎌',tag:'Apparel',type:'oversized',category:'Apparel',desc:'Galaxy series',isNew:true,anime:'Mixed'},
  {id:'p110',name:'Galaxy Tee 1',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Tee shirt',isNew:false,anime:'Mixed'},
  {id:'p111',name:'Mystic Hoodie 1',price:1999,img:'🎌',tag:'Apparel',type:'hoodie',category:'Apparel',desc:'Mystic design',isNew:true,anime:'Mixed'},
  {id:'p112',name:'Mystic Tee 1',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Tee shirt',isNew:false,anime:'Mixed'},
  {id:'p113',name:'Cosmic Hoodie 1',price:2099,img:'🎌',tag:'Apparel',type:'jacket',category:'Apparel',desc:'Cosmic jacket',isNew:true,anime:'Mixed'},
  {id:'p114',name:'Cosmic Tee 1',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Tee shirt',isNew:false,anime:'Mixed'},
  {id:'p115',name:'Eternal Hoodie 1',price:1999,img:'🎌',tag:'Apparel',type:'oversized',category:'Apparel',desc:'Eternal series',isNew:false,anime:'Mixed'},
  {id:'p116',name:'Eternal Tee 1',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Tee shirt',isNew:false,anime:'Mixed'},
  {id:'p117',name:'Abyss Hoodie 1',price:2099,img:'🎌',tag:'Apparel',type:'hoodie',category:'Apparel',desc:'Abyss design',isNew:true,anime:'Mixed'},
  {id:'p118',name:'Abyss Tee 1',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Tee shirt',isNew:false,anime:'Mixed'},
  {id:'p119',name:'Void Hoodie 1',price:2199,img:'🎌',tag:'Apparel',type:'oversized',category:'Apparel',desc:'Void oversized',isNew:true,anime:'Mixed'},
  {id:'p120',name:'Void Tee 1',price:799,img:'👕',tag:'Apparel',type:'tee',category:'Apparel',desc:'Tee shirt',isNew:false,anime:'Mixed'}
];
